### ISSUE TITLE
Chart showing wrong date time stamp

### ISSUE THREAD

**Issue by chrisolver** [rlightner/public-BrewStatus#13]
![image](https://cloud.githubusercontent.com/assets/5326609/22858706/2a16d7d6-f119-11e6-9c7d-2a810f417c12.png)
![image](https://cloud.githubusercontent.com/assets/5326609/22858708/3595c1e4-f119-11e6-8573-bc3a602d8b89.png)
 Set as correct time zone (AEST) but chart shows times in US time by the looks of it.

**Comment by csmales** [comment]
Hi,

I am getting the same here - I am in AWST +8

**Comment by rlightner** [comment]
Is this still an issue?

**Comment by EmDubeu** [comment]
Yes

On Feb 21, 2017 23:02, "Raine Lightner" <notifications@github.com> wrote:

Is this still an issue?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rlightner/public-BrewStatus/issues/13#issuecomment-281586894>,
or mute the thread

**Comment by ghost** [comment]
+1 - I didn't notice this before, seemed correct on my first brew, but current brew is showing incorrectly.
